### ISSUE TITLE
npm run auth无法启动

### ISSUE THREAD

**Issue by wyh137815840** [beetcb/sosf#14]
git clone -b tcb-scf https://github.com/beetcb/sosf.git && cd platforms/cloudbase/sosf/
npm i
npm run auth
# 在此根据提示开始配置

似乎在platforms/cloudbase/sosf/目录下没有npm的运行脚本（我是纯小白，可能描述的不是很准确）

**Comment by yaonyan** [comment]
@wyh137815840 你说的没错，说明文档确实遗留了一些问题，我刚刚更新了文档，请重试一下
