### ISSUE TITLE
你好，请问可以通过一个key串获取目录树的这个功能吗

### ISSUE THREAD

**Issue by veink-y** [beetcb/sosf#8]
这样方便在分享文件夹的时候，知道具体的文件链接

**Comment by yaonyan** [comment]
谢谢反馈，目前不支持类似功能，近期会考虑实现。

我初步的想法是这样：

1. 访问任意文件夹
    ```
    GET /pathName
    ```
    => 

    ```json
      {
        "path1": "keyId1",
        "path2": "keyId2",
        "file": "keyId3"
      }
    ```
   返回文件或文件夹及对应 key

2. 使用任意 key 访问
    ```text
    GET ?key=keyId1
    ```
    => 

    ```json
        {
          "path21": "keyId1",
          "path22": "keyId2",
          "filex": "keyId3"
        }
    ```
    返回和 1 相同内容

你觉得如何 @veink-y

**Comment by veink-y** [comment]
1. 可以，但是我觉得最好加一个验证环节，即需要一定的密码标识才能获取到这个返回数据（防止爬虫或者别有用心）
2. keyID这个位置可以直接拼接成一个链接，方便直接点击？
3. 也即是参数设置两个，一个path，一个是密码，返回值为
{
      "path21": url21（带上密码）,
      "path22": url21（带上密码）,
      "filex": url21（拼接后的链接）
    }
4. 为了减少api调用，可以单次只返回当前目录下的文件和文件夹，不下挖所有路径

**Comment by yaonyan** [comment]
对应序号回答哈:


3. 这里只需要返回链接就行
    ```json
      {
        "path1": "link1?key=keyId1&access_key=123",
        "path2": "link2?key=keyId2&access_key=123",
        "file": "link3?key=keyId3"
      }
    ```
4. 这是微软 API 的默认行为，不用特别考虑


补充：还应实现一个分页链接

**Comment by veink-y** [comment]
厉害👍🏻，这样就能很好实现了，给你点赞

**Comment by yaonyan** [comment]
腾讯云部署的此功能基本完成，你可以更新试试 @veink-y 

我这有个测试地址：

https://static.beetcb.com/

**Comment by veink-y** [comment]
你好，抱歉这么久才恢复，我之前部署的vercel，现在我换成tcb手动部署时，当运行到` tcb fn deploy` 时候，系统返回
```
? 没有指定需要部署的云函数，是否部署配置文件中的全部云函数？ Yes
√ 成功部署 0 个函数
× 1 个云函数部署失败
```
请问，这里手动部署时是否有什么步骤错误？

**Comment by veink-y** [comment]
我尝试在cloudbaserc.json中秀给了 env.ENV_ID 为手动免费空间的 环境id，能部署上去，但是报错，后续无法判断错误具体原因，请问能给个完整的手动部署的文档么？感谢

**Comment by veink-y** [comment]
我再次尝试，将 ENV_ID 配置在了 .env 文件里 并再次部署成功，但是该次出现400错误
```
请求ID: 0974c027c6fac4d1570e2
错误码: INVOKE_FUNCTION_FAILED
错误信息: Code: -1 ScfRequestId: -a5d4-525400b8ee5a Error: TypeError: Cannot read property 'access_token' of undefined at exports.getToken (/var/user/api/sosf.js:76:16)
```

**Comment by veink-y** [comment]
okay,跌跌撞撞我还是配通了，最后需要在云函数的env里再次写入.env信息

**Comment by yaonyan** [comment]
手动部署的话多看看最好使用云开发框架 `tcb framework deploy -e "$ENV_ID"`  而不是云函数，因为它可以自动配置好 ENV_ID

然后我仓库现在有个 CD，可以自动部署到云开发，还没写到文档里去 @veink-y

**Comment by veink-y** [comment]
我已经尝试了当前的新功能，有以下几点：

1.  基于当前的链接前台被按钮替代，则这里无法显式地复制链接，如果可能，这里的前台页面可以展示链接并能批量复制最佳
2.  没想到你还做了检索，超级棒了，很方便，意料之外的惊喜
3.  access key是下次更新的内容吗

**Comment by yaonyan** [comment]
1. 会考虑找个库实现（总之要把服务器传到前端的代码优化地越少越好）
2. 列表和检索是 Grid.js 这个库的功能，节省了我不少代码量
3. 其实这次迭代就包含了 access_key，还没写文档 😂

**Comment by veink-y** [comment]
等待你的文档

**Comment by yaonyan** [comment]
@veink-y 文档已更（终于 ~~ ）

**Comment by veink-y** [comment]
周末终于有空来折腾一下了！！！

我fork后配置好serect后运行action，但是access_key没起作用，依然是无需access_key就能访问目录树

**Comment by yaonyan** [comment]
@veink-y 修复了，你先用我的账号测试一下，看看有没有其它问题

https://static.beetcb.com/

```ts
access_key = 123
```

**Comment by yaonyan** [comment]
如果没问题就可以用 GitHub 这个新功能更新代码，很方便：

![image](https://user-images.githubusercontent.com/63141491/120069090-a46b2c00-c0b6-11eb-8a7a-893d6c7eb6ab.png)

之后 CD 就会自动部署啦，一气呵成！

**Comment by veink-y** [comment]
棒，这个新功能超级方便了
我又来提功能了：
可不可以把上一级的链接也置顶放呢，就像linux目录树用 `..` 来代替上级目录树，因为试用过程中发现有这个需求
如下图所示：
[![2EqKVU.png](https://z3.ax1x.com/2021/05/30/2EqKVU.png)](https://imgtu.com/i/2EqKVU)

**Comment by beetcb** [comment]
@veink-y 

可以，增加了可用性

只是我实在不知道把它放哪 😂，目前的界面是这样的

![Snipaste_2021-05-31_18-47-30](https://user-images.githubusercontent.com/63141491/120183474-52571180-c242-11eb-99af-d127e3207882.png)

**Comment by yaonyan** [comment]
@veink-y 

今天早上更新了 **上级目录** 和 **链接复制** 功能，请部署体验：

![sosf-latest](https://user-images.githubusercontent.com/63141491/120266035-aeb64180-c2d3-11eb-9cc8-c01b2f22f837.png)

**Comment by veink-y** [comment]
已更新，超级棒！！！
感谢作者！！！

**Comment by yaonyan** [comment]
> 已更新，超级棒！！！
> 感谢作者！！！

谢谢，没有什么问题的话这个 Issue 可以关掉了
